### PR TITLE
JavaScript Capstone: Implement Likes and Comment

### PR DESCRIPTION
**Pull request by dselasea**
In this pull request I 
- Implemented the likes api
- Implemented the comments api
- added comment popup with minimal styles

### CODE REVIEW

**Review by BB-Simon — APPROVED** [review]
Hi @dselasea 
Awesome, Good job so far,

- [ ] 1. Implemented the likes api
- [ ] 2. Implemented the comments api
- [ ] 3. added comment popup with minimal styles

**Review by BB-Simon — APPROVED** [review]
Hi @dselasea 
Good job with the UI design, However still there are some issues you need to work on to move to the next step:

- [ ] Please kindly fix the linter errors

**Comment by dselasea** [comment]
I added some styles to the CSS and fixed linter errors

**Review by BB-Simon — APPROVED** [review]
Hi @dselasea 
Good job with fixing the linter errors

**Pull request merged**
